// Auto-generated by print_constants.c — do not edit.
export const PAGE_SIZE = 0x4000;
export const PROT_READ = 0x1;
export const PROT_WRITE = 0x2;
export const MAP_SHARED = 0x1;
export const MAP_PRIVATE = 0x2;
export const MAP_FIXED = 0x10;
export const MAP_ANON = 0x1000;
export const O_RDWR = 0x2;
export const MS_ASYNC = 0x1;
export const MS_SYNC = 0x10;
export const LIBC = "libSystem.B.dylib";
