#include <stdio.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <unistd.h>

int main(void) {
    printf("// Auto-generated by print_constants.c — do not edit.\n");
    printf("export const PAGE_SIZE = 0x%lx;\n", (long)getpagesize());
    printf("export const PROT_READ = 0x%x;\n", PROT_READ);
    printf("export const PROT_WRITE = 0x%x;\n", PROT_WRITE);
    printf("export const MAP_SHARED = 0x%x;\n", MAP_SHARED);
    printf("export const MAP_PRIVATE = 0x%x;\n", MAP_PRIVATE);
    printf("export const MAP_FIXED = 0x%x;\n", MAP_FIXED);
#ifdef MAP_ANON
    printf("export const MAP_ANON = 0x%x;\n", MAP_ANON);
#elif defined(MAP_ANONYMOUS)
    printf("export const MAP_ANON = 0x%x;\n", MAP_ANONYMOUS);
#endif
    printf("export const O_RDWR = 0x%x;\n", O_RDWR);
    printf("export const MS_ASYNC = 0x%x;\n", MS_ASYNC);
    printf("export const MS_SYNC = 0x%x;\n", MS_SYNC);
#ifdef __APPLE__
    printf("export const LIBC = \"libSystem.B.dylib\";\n");
#else
    printf("export const LIBC = \"libc.so.6\";\n");
#endif
    return 0;
}
